### ISSUE TITLE
Unable to remove empty H elements

### ISSUE THREAD

**Issue by larscwallin** [ShareMyWorld/Squire#3]

**Comment by kpx** [comment]
When after a blockquote/aside

**Comment by larscwallin** [comment]
Not so fast sir ;)

Still unable to remove them when they are first in the text, and when they are directly after images.

They should work just as aside and bq does. After the last child is removed from the H-tag it should be removed from the DOM and the cursor should end up at the end of the previous paragraph.

**Comment by kpx** [comment]
changed squire backspace in empty heading behavior to the smw one.
